import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireNormalUser } from "@/lib/auth/authorization";
import { resolveJoinPlan } from "@/lib/checkout/plans";
import { clientEnv,getServerEnv } from "@/lib/env";
const schema=z.object({planKey:z.string()});
function sameOrigin(request:NextRequest){const origin=request.headers.get("origin");return !origin||new URL(origin).host===request.nextUrl.host;}
export async function POST(request:NextRequest){if(!sameOrigin(request))return NextResponse.json({error:"Invalid request."},{status:403});const user=await requireNormalUser();if(!user)return NextResponse.json({error:"Sign in required."},{status:401});let input;try{input=schema.parse(await request.json());}catch{return NextResponse.json({error:"Choose a valid plan."},{status:400});}const plan=resolveJoinPlan(input.planKey);const env=getServerEnv();if(!plan||!env.LEMONSQUEEZY_API_KEY||!env.LEMONSQUEEZY_STORE_ID)return NextResponse.json({error:"Secure payment is not configured yet."},{status:503});const admin=createAdminClient();const expiresAt=new Date(Date.now()+30*60*1000).toISOString();const {data:intent,error:intentError}=await admin.from("checkout_intents").insert({user_id:user.id,plan_key:plan.key,lemon_variant_id:plan.variantId,status:"pending",customer_email:user.email,expires_at:expiresAt}).select("id").single();if(intentError||!intent)return NextResponse.json({error:"Could not start secure payment."},{status:500});const redirectUrl=`${clientEnv.NEXT_PUBLIC_APP_URL}/checkout/success?intent=${encodeURIComponent(intent.id)}`;const payload={data:{type:"checkouts",attributes:{product_options:{enabled_variants:[Number(plan.variantId)],redirect_url:redirectUrl},checkout_options:{embed:true,media:false,logo:true,desc:true},checkout_data:{email:user.email,custom:{checkout_intent_id:intent.id}},expires_at:expiresAt},relationships:{store:{data:{type:"stores",id:String(env.LEMONSQUEEZY_STORE_ID)}},variant:{data:{type:"variants",id:String(plan.variantId)}}}}};let remote;try{remote=await fetch("https://api.lemonsqueezy.com/v1/checkouts",{method:"POST",headers:{Accept:"application/vnd.api+json","Content-Type":"application/vnd.api+json",Authorization:`Bearer ${env.LEMONSQUEEZY_API_KEY}`},body:JSON.stringify(payload),cache:"no-store"});}catch{remote=null;}if(!remote||!remote.ok){await admin.from("checkout_intents").update({status:"failed",updated_at:new Date().toISOString()}).eq("id",intent.id);return NextResponse.json({error:"Could not open secure payment."},{status:502});}const checkout=await remote.json() as {data?:{id?:string;attributes?:{url?:string}}};const url=checkout.data?.attributes?.url;if(!url){await admin.from("checkout_intents").update({status:"failed"}).eq("id",intent.id);return NextResponse.json({error:"Could not open secure payment."},{status:502});}await admin.from("checkout_intents").update({status:"checkout_created",lemon_checkout_id:checkout.data?.id??null,updated_at:new Date().toISOString()}).eq("id",intent.id);return NextResponse.json({checkoutUrl:url,intentId:intent.id});}

