import { PastDueBanner } from "@/components/account/past-due-banner";
import { DashboardScrollReveal } from "@/components/dashboard/dashboard-scroll-reveal";
import { ButtonLink } from "@/components/marketing/button-link";
import { Badge } from "@/components/ui/badge";
import { accountStatusBadgeVariant, resolveBillingPortalUrl } from "@/lib/account/types";
import type { AccountSubscriptionSummary } from "@/lib/account/types";
import { routes } from "@/lib/routes";

type Props = { summary: AccountSubscriptionSummary };

export function AccountBillingView({ summary }: Props) {
  const portalUrl = resolveBillingPortalUrl(summary);
  const statusVariant = accountStatusBadgeVariant(summary);
  const isTrial = summary.isTrialActive && summary.status === "trial";
  return <div className="account-billing-view mx-auto max-w-3xl space-y-8">
    <PastDueBanner summary={summary} />
    <DashboardScrollReveal><header><p className="font-[family-name:var(--font-mono)] text-[11px] uppercase tracking-[0.08em] text-[var(--color-brand)]">Billing management</p><h1 className="mt-2 font-[family-name:var(--font-display)] text-[clamp(2rem,5vw,2.75rem)] font-black leading-[0.95] tracking-[-0.03em]">{isTrial ? "Your free trial" : "Plan and payment details"}</h1><p className="mt-3 text-[length:var(--text-body)] text-[var(--color-text-muted)]">{isTrial ? "You have full Basscally Hub access during your 7-Day Free Trial. No card is required today." : "Invoices, card updates, and plan changes are handled in the secure billing portal."}</p></header></DashboardScrollReveal>
    <DashboardScrollReveal delayMs={60}><section className="rounded-[var(--radius-xl)] border border-[var(--color-border)] bg-[var(--color-surface)] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-[family-name:var(--font-display)] text-xl font-bold">Current plan</h2><p className="mt-1 text-sm text-[var(--color-text-muted)]">{summary.email}</p></div><Badge variant={statusVariant}>{summary.statusLabel}</Badge></div><dl className="mt-6 space-y-4 border-t border-[var(--color-border)] pt-6"><div className="flex justify-between gap-4 text-sm"><dt className="text-[var(--color-text-muted)]">Plan</dt><dd className="font-semibold">{summary.planLabel}</dd></div><div className="flex justify-between gap-4 text-sm"><dt className="text-[var(--color-text-muted)]">Price</dt><dd className="font-semibold">{summary.priceLabel}</dd></div><div className="flex justify-between gap-4 text-sm"><dt className="text-[var(--color-text-muted)]">Status</dt><dd className="font-semibold">{summary.statusLabel}</dd></div><div className="flex justify-between gap-4 text-sm"><dt className="text-[var(--color-text-muted)]">{isTrial ? "Trial ends" : "Period end"}</dt><dd className="font-semibold">{isTrial ? summary.trialEndLabel : summary.periodEndLabel}</dd></div><div className="flex justify-between gap-4 text-sm"><dt className="text-[var(--color-text-muted)]">{isTrial ? "Time remaining" : "Next renewal"}</dt><dd className="font-semibold">{isTrial ? summary.trialRemainingLabel : summary.renewalLabel}</dd></div><div className="flex justify-between gap-4 text-sm"><dt className="text-[var(--color-text-muted)]">Access</dt><dd className="font-semibold">{summary.hasAccess ? "Full Hub access" : "Limited - renew to restore access"}</dd></div></dl>{isTrial ? <p className="mt-8 text-sm text-[var(--color-text-muted)]">Founding price locked at $1.50/month when membership activation is available.</p> : <div className="mt-8 flex flex-wrap gap-3 max-[680px]:flex-col">{portalUrl ? <ButtonLink href={portalUrl} className="landing-cta-glow max-[680px]:w-full" target="_blank" rel="noopener noreferrer">Open billing portal</ButtonLink> : <ButtonLink href={routes.member.accountBillingPortal} className="landing-cta-glow max-[680px]:w-full">Open billing portal</ButtonLink>}<ButtonLink href={routes.member.account} variant="secondary" className="max-[680px]:w-full">Back to membership</ButtonLink></div>}</section></DashboardScrollReveal>
  </div>;
}